const colors = {
  light: {
    text:               "#1E2D33",
    tint:               "#5BC8C0",
    background:         "#F7EEE5",
    foreground:         "#1E2D33",
    card:               "#FFFFFF",
    cardForeground:     "#1E2D33",
    primary:            "#5BC8C0",
    primaryForeground:  "#FFFFFF",
    secondary:          "#EDAA8F",
    secondaryForeground:"#1E2D33",
    muted:              "#EAE2DA",
    mutedForeground:    "#697880",
    accent:             "#E87A50",
    accentForeground:   "#FFFFFF",
    destructive:        "#D45270",
    destructiveForeground: "#FFFFFF",
    border:             "#D9CFC7",
    input:              "#D4C9BD",
  },
  dark: {
    text:               "#EDE5DF",
    tint:               "#63CEC6",
    background:         "#131F22",
    foreground:         "#EDE5DF",
    card:               "#19282C",
    cardForeground:     "#EDE5DF",
    primary:            "#63CEC6",
    primaryForeground:  "#131F22",
    secondary:          "#293B3F",
    secondaryForeground:"#EDE5DF",
    muted:              "#202E32",
    mutedForeground:    "#A69A90",
    accent:             "#E07F57",
    accentForeground:   "#131F22",
    destructive:        "#D45270",
    destructiveForeground: "#EDE5DF",
    border:             "#293B3F",
    input:              "#2E3F44",
  },
  radius: 6,
};

export default colors;
